# Generated by Django 3.2.8 on 2022-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_tag',
            field=models.CharField(default='Article Title', max_length=200),
        ),
    ]
