# Generated by Django 3.2.8 on 2022-01-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejournal', '0002_article_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_tag',
            field=models.CharField(max_length=200),
        ),
    ]
