# Generated by Django 3.2.8 on 2021-11-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211119_0753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
