# Generated by Django 3.2.8 on 2021-11-28 00:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20211127_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogComment',
            new_name='PostComment',
        ),
    ]
