# Generated by Django 3.2.8 on 2021-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_blogcomment_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='subject',
            new_name='subject_line',
        ),
    ]
