# Generated by Django 3.2.8 on 2021-11-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_subject_postcomment_subject_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
