# Generated by Django 3.2.8 on 2021-12-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
