# Generated by Django 3.2.8 on 2021-12-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
