# Generated by Django 3.2.8 on 2021-10-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_discount',
            new_name='is_onsale',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='onsale_price',
        ),
    ]
